import Head from "next/head";
import { MarkGithubIcon } from '@primer/octicons-react';
import styles from "@/styles/index.module.scss";
import GithubAutocomplete from "@/components/githubAutocomplete/GithubAutocomplete";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.Home}>
        <main className={styles.main}>
          <MarkGithubIcon size={48} />
          <GithubAutocomplete />
        </main>
      </div>
    </>
  );
}
